version: '3'

services:
  psql:
    image: 'postgres:13'
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: macpepdb_dev
