import unittest

from trypperdb.proteomics.enzymes.trypsin import Trypsin
from trypperdb.models.protein import Protein
from trypperdb.models.peptide import Peptide

# Peptides for Leptin (UniProt accession Q257X2) digested with 3 missed cleavages, length 0 - 60
# Tested with https://web.expasy.org/peptide_mass/
# Leucine and Isoleucine are replaced with J already! 
DESIRED_RESULTS = {
    "VTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSRNVJQJSNDJENJRDJJHJJAASK",
    "NVJQJSNDJENJRDJJHJJAASKSCPJPQVRAJESJESJGVVJEASJYSTEVVAJSR",
    "DJJHJJAASKSCPJPQVRAJESJESJGVVJEASJYSTEVVAJSRJQGSJQDMJR",
    "QRVTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSRNVJQJSNDJENJR",
    "JNDJSHTQSVSSKQRVTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSR",
    "SCPJPQVRAJESJESJGVVJEASJYSTEVVAJSRJQGSJQDMJRQJDJSPGC",
    "MDQTJAJYQQJJASJPSRNVJQJSNDJENJRDJJHJJAASKSCPJPQVR",
    "VTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSRNVJQJSNDJENJR",
    "SCPJPQVRAJESJESJGVVJEASJYSTEVVAJSRJQGSJQDMJR",
    "AJESJESJGVVJEASJYSTEVVAJSRJQGSJQDMJRQJDJSPGC",
    "DJJHJJAASKSCPJPQVRAJESJESJGVVJEASJYSTEVVAJSR",
    "MDQTJAJYQQJJASJPSRNVJQJSNDJENJRDJJHJJAASK",
    "QRVTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSR",
    "TJVTRJNDJSHTQSVSSKQRVTGJDFJPGJHPJJSJSK",
    "VTGJDFJPGJHPJJSJSKMDQTJAJYQQJJASJPSR",
    "AJESJESJGVVJEASJYSTEVVAJSRJQGSJQDMJR",
    "CGPJYRFJWJWPYJSYVEAVPJRKVQDDTK",
    "SCPJPQVRAJESJESJGVVJEASJYSTEVVAJSR",
    "JNDJSHTQSVSSKQRVTGJDFJPGJHPJJSJSK",
    "MDQTJAJYQQJJASJPSRNVJQJSNDJENJR",
    "NVJQJSNDJENJRDJJHJJAASKSCPJPQVR",
    "FJWJWPYJSYVEAVPJRKVQDDTKTJJK",
    "MRCGPJYRFJWJWPYJSYVEAVPJRK",
    "MRCGPJYRFJWJWPYJSYVEAVPJR",
    "VQDDTKTJJKTJVTRJNDJSHTQSVSSK",
    "CGPJYRFJWJWPYJSYVEAVPJRK",
    "FJWJWPYJSYVEAVPJRKVQDDTK",
    "CGPJYRFJWJWPYJSYVEAVPJR",
    "AJESJESJGVVJEASJYSTEVVAJSR",
    "TJJKTJVTRJNDJSHTQSVSSKQR",
    "NVJQJSNDJENJRDJJHJJAASK",
    "TJJKTJVTRJNDJSHTQSVSSK",
    "FJWJWPYJSYVEAVPJRK",
    "TJVTRJNDJSHTQSVSSKQR",
    "QRVTGJDFJPGJHPJJSJSK",
    "FJWJWPYJSYVEAVPJR",
    "MDQTJAJYQQJJASJPSR",
    "TJVTRJNDJSHTQSVSSK",
    "JQGSJQDMJRQJDJSPGC",
    "DJJHJJAASKSCPJPQVR",
    "VTGJDFJPGJHPJJSJSK",
    "KVQDDTKTJJKTJVTR",
    "VQDDTKTJJKTJVTR",
    "JNDJSHTQSVSSKQR",
    "NVJQJSNDJENJR",
    "JNDJSHTQSVSSK",
    "KVQDDTKTJJK",
    "VQDDTKTJJK",
    "JQGSJQDMJR",
    "DJJHJJAASK",
    "TJJKTJVTR",
    "MRCGPJYR",
    "SCPJPQVR",
    "KVQDDTK",
    "QJDJSPGC",
    "CGPJYR",
    "VQDDTK",
    "TJVTR",
    "TJJK",
    "MR",
    "QR",
    "K"
}


class TrypsinTestCase(unittest.TestCase):
    def test_digest(self):
        # Using Leptin (UniProt  accession: Q257X2)
        leptin = Protein("Q257X2", "LEP_CAPHI", "Leptin", "MRCGPLYRFLWLWPYLSYVEAVPIRKVQDDTKTLIKTIVTRINDISHTQSVSSKQRVTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSRNVIQISNDLENLRDLLHLLAASKSCPLPQVRALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLRQLDLSPGC", 9925, "UP000291000", True)
        trypsin = Trypsin(3, 0, 60)
        peptides = trypsin.digest(leptin)

        self.assertEqual(len(DESIRED_RESULTS), len(peptides))

        for peptide in peptides:
            self.assertTrue(peptide.sequence in DESIRED_RESULTS)
